# Generated by Django 3.2.9 on 2023-01-25 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_texnikum'),
        ('donation', '0002_alter_donation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='markaz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.markaz'),
        ),
    ]
