# Generated by Django 3.2.9 on 2022-12-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_seen',
            new_name='completed',
        ),
    ]
