# Generated by Django 3.2.9 on 2022-12-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_rename_receiver_notification_receiver_markaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[(1, 'Kelib tushdi'), (2, 'Tasdiqlandi'), (3, 'Rad etildi')], max_length=1, null=True),
        ),
    ]
