# Generated by Django 3.2.9 on 2022-12-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='rejection_reason',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
