# Generated by Django 3.2.9 on 2023-01-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_remove_notification_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='rejection_reason',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
