# Generated by Django 3.2.9 on 2023-01-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_donationnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationnotification',
            old_name='juvenile',
            new_name='donation',
        ),
    ]
