# Generated by Django 3.2.9 on 2022-12-06 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country_regions', '0001_initial'),
        ('info', '0002_auto_20221206_0247'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Juvenile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'juvenile',
            },
        ),
        migrations.CreateModel(
            name='JuvenileAcceptCenterInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('determined_location', models.CharField(choices=[(1, 'Bozor'), (2, 'Yer-to‘la va chor-doq'), (3, "Ko'cha"), (4, 'Boshqa joylar'), (5, 'Boshqa davlatlardan')], default=None, max_length=60, null=True)),
                ('count_came_back_to_center', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('arrived_date', models.DateTimeField(blank=True, null=True)),
                ('arrived_reason', models.CharField(choices=[(1, 'IIB qarori'), (1, 'Sud ajrimi')], default=None, max_length=60, null=True)),
                ('prophylactic_list', models.BooleanField(default=False, null=True)),
                ('arrived_reason_file', models.FileField(blank=True, null=True, upload_to='arrived_reason_file/')),
                ('have_been_in_rotm_reason', models.CharField(choices=[(1, 'Qaror bilan chiqarilgan'), (2, 'Qochgan')], default=None, max_length=60, null=True)),
                ('have_been_in_itm_reason', models.CharField(choices=[(1, 'Qaror bilan chiqarilgan'), (2, 'Qochgan')], default=None, max_length=60, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_juvenileacceptcenterinfo_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'juvenile_accept_center_info',
            },
        ),
        migrations.CreateModel(
            name='JuvenileParent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('pinfl', models.CharField(blank=True, max_length=14)),
                ('birth_date', models.DateField()),
                ('employment', models.TextField(blank=True, max_length=1500, null=True)),
                ('is_abroad', models.BooleanField(default=None, null=True)),
                ('is_wanted', models.BooleanField(default=None, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_juvenileparent_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_juvenileparent_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parent_juvenile',
            },
        ),
        migrations.CreateModel(
            name='ParentInfoJuvenile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marital_status', models.CharField(choices=[(1, 'Ota-onasi bor'), (2, "Otasi yoki onasi yo'q"), (3, "Vasiy qaramog'ida"), (4, "Hech kimi yo'q")], default=None, max_length=60, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_parentinfojuvenile_created_by', to=settings.AUTH_USER_MODEL)),
                ('juvenile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='juvenile.juvenile')),
            ],
            options={
                'db_table': 'parent_info_juvenile',
            },
        ),
        migrations.CreateModel(
            name='UnidentifiedJuvenile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('father_name', models.CharField(max_length=255, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('photo', models.ImageField(null=True, upload_to='unidentified_juveniles/')),
                ('birth_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth_district', to='info.district')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_unidentifiedjuvenile_created_by', to=settings.AUTH_USER_MODEL)),
                ('markaz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.markaz')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_unidentifiedjuvenile_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'unidentified_juvenile',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_type', models.CharField(choices=[(1, 'Ota'), (2, 'Ona'), (3, 'Muqobil (Alternativ) boquvchi')], default=None, max_length=60, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juvenile.juvenileparent')),
                ('parent_info_juvenile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juvenile.parentinfojuvenile')),
            ],
            options={
                'db_table': 'relationship',
            },
        ),
        migrations.CreateModel(
            name='ProphylacticInspector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('inspector_id', models.IntegerField(blank=True, null=True)),
                ('pinfl', models.CharField(max_length=14)),
                ('inspector_type', models.CharField(choices=[(1, 'Inspektor'), (2, 'Psixolog'), (3, 'Markaz xodimi'), (4, 'Boshqalar')], default=None, max_length=30, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_prophylacticinspector_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_prophylacticinspector_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prophylactic_inspector',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfoJuvenile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('pinfl', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('photo', models.ImageField(null=True, upload_to='juveniles/')),
                ('passport_type', models.CharField(choices=[(1, 'Biometrik pasport'), (2, 'ID-karta'), (3, "Tug'ilganlik haqida guvohnoma"), (4, 'Horijiy davlat hujjatlari'), (5, 'Boshqalar')], max_length=30, null=True)),
                ('passport_seria', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('reference_type', models.FileField(blank=True, null=True, upload_to='reference_types/')),
                ('birth_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth', to='info.district')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_personalinfojuvenile_created_by', to=settings.AUTH_USER_MODEL)),
                ('foreign_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country', to='country_regions.country')),
                ('juvenile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile', to='juvenile.juvenile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_personalinfojuvenile_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_info_juvenile',
            },
        ),
        migrations.AddField(
            model_name='parentinfojuvenile',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='parent', through='juvenile.Relationship', to='juvenile.JuvenileParent'),
        ),
        migrations.AddField(
            model_name='parentinfojuvenile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_parentinfojuvenile_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JuvenileMonitoringInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('speciality', models.CharField(blank=True, max_length=255, null=True)),
                ('class_group', models.CharField(blank=True, max_length=255, null=True)),
                ('class_leader', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('assimilation', models.CharField(blank=True, max_length=255, null=True)),
                ('behavior', models.CharField(blank=True, max_length=255, null=True)),
                ('mastery', models.CharField(choices=[(1, "A'lo"), (2, 'Yaxshi'), (3, 'Qoniqarli'), (4, 'Qoniqarsiz')], default=None, max_length=60, null=True)),
                ('character', models.CharField(choices=[(1, 'Yaxshi'), (2, 'Qoniqarli'), (3, 'Qoniqarsiz')], default=None, max_length=60, null=True)),
                ('is_action_been_taken', models.BooleanField(default=False, null=True)),
                ('file_action_been_taken', models.FileField(blank=True, null=True, upload_to='action_been_taken/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_juvenilemonitoringinfo_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_juvenilemonitoringinfo_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'juvenile_monitoring_info',
            },
        ),
        migrations.CreateModel(
            name='JuvenileMedicalList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_center_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juvenile.juvenileacceptcenterinfo')),
                ('medical_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.medicallist')),
            ],
            options={
                'db_table': 'juvenile_medical_list',
            },
        ),
        migrations.CreateModel(
            name='JuvenileEmploymentInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_military', models.BooleanField(blank=True, default=False, null=True)),
                ('employment_inspector', models.CharField(blank=True, max_length=255, null=True)),
                ('neighborhood_coach', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_speciality', models.CharField(blank=True, max_length=255, null=True)),
                ('employment', models.CharField(blank=True, max_length=255, null=True)),
                ('not_applied_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('accepted_school', models.CharField(blank=True, max_length=255, null=True)),
                ('high_school', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_school', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_education_type', models.CharField(choices=[(1, "Oliy ta'lim"), (2, "O'rta maxsus ta'lim")], default=None, max_length=60, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_juvenileemploymentinfo_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_juvenileemploymentinfo_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'juvenile_employment_info',
            },
        ),
        migrations.CreateModel(
            name='JuvenileDistributedInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distribution_type', models.CharField(choices=[(1, 'Oila'), (2, 'Vasiylik organi orqali'), (3, 'ITM'), (4, "RO'TM"), (5, "Sog'liqni saqlash muassasasi"), (6, 'Boshqa markazga yuborish'), (7, 'Boshqa davlatga yuborish'), (8, 'Boshqalar')], default=None, max_length=60, null=True)),
                ('basis_distribution', models.CharField(choices=[(1, 'Markaz xulosasi'), (2, 'Hokim qarori'), (3, "Tegishli vazirlik/tashkilot yo'llanmasi"), (4, 'Sud ajrimi'), (5, 'SSV hulosasi'), (6, 'Notarial ishonchnoma')], default=None, max_length=60, null=True)),
                ('health_condition', models.FileField(blank=True, null=True, upload_to='health_condition/')),
                ('skills_hobbies', models.FileField(blank=True, null=True, upload_to='skills_hobbies/')),
                ('organization_psyhologs_name', models.CharField(blank=True, max_length=255, null=True)),
                ('level_kinkdship', models.CharField(choices=[(1, 'Ota'), (2, 'Ona'), (3, 'Aka'), (4, 'Opa'), (5, 'Amaki'), (6, 'Amma'), (7, "Tog'a"), (8, 'Xola'), (9, 'Bobo'), (10, 'Buvi'), (11, 'Vaqinchalik vakil')], default=None, max_length=60, null=True)),
                ('type_guardianship', models.CharField(choices=[(1, 'Vasiy'), (2, 'Homiy'), (3, 'Patronat'), (4, 'Farzandlik'), (5, 'Mehribonlik uyi'), (6, 'Oilaviy bolalar uyi'), (8, 'SOS bolalar shaharchasi'), (8, 'SOS bolalar shaharchasi')], default=None, max_length=60, null=True)),
                ('itm_direction', models.CharField(choices=[(1, 'Harbiy'), (2, "Ma'daniyat va sa'nat"), (3, 'Sport'), (4, "Fan yo'nalishi"), (5, 'Boshqalar')], default=None, max_length=60, null=True)),
                ('itm_name', models.CharField(max_length=255, null=True)),
                ('rotm_type', models.CharField(choices=[(1, "Qiz bolalar uchun RO'TM"), (2, "O'g'il bolalar uchun RO'TM")], default=None, max_length=60, null=True)),
                ('basis_sending_file', models.FileField(blank=True, null=True, upload_to='basis_sending_file/')),
                ('psyhology_condition', models.FileField(blank=True, null=True, upload_to='psyhology_condition/')),
                ('organization_directors_name', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_coach_name', models.CharField(blank=True, max_length=255, null=True)),
                ('foreign_to_whom_given', models.CharField(choices=[(1, 'Ota-onasi yoki uni o‘rnini bosuvchi shaxsga'), (2, 'Chet-el Elchixonasiga'), (3, 'Chet-el Markazi xodimiga')], default=None, max_length=60, null=True)),
                ('is_training', models.BooleanField(default=False, null=True)),
                ('type_healthcare_facility', models.CharField(choices=[(1, 'Ruhiy-asab kasalliklari dispanseri'), (2, 'Narkologiya dispanseri'), (3, 'Teri-tanosil dispanseri'), (4, 'Sil kasaliklari dispanseri'), (5, 'Sog‘ligida nuqsoni bor bolalar muassasasi')], default=None, max_length=60, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_juveniledistributedinfo_created_by', to=settings.AUTH_USER_MODEL)),
                ('itm_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itm', to='info.district')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_juveniledistributedinfo_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'juvenile_distributed_info',
            },
        ),
        migrations.AddField(
            model_name='juvenileacceptcenterinfo',
            name='inspector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prophylactic_inspector', to='juvenile.prophylacticinspector'),
        ),
        migrations.AddField(
            model_name='juvenileacceptcenterinfo',
            name='medical_list',
            field=models.ManyToManyField(blank=True, through='juvenile.JuvenileMedicalList', to='info.MedicalList'),
        ),
        migrations.AddField(
            model_name='juvenileacceptcenterinfo',
            name='sub_reason_bringing_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_reason_bringing_child', to='info.subreasonbringingchild'),
        ),
        migrations.AddField(
            model_name='juvenileacceptcenterinfo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_juvenileacceptcenterinfo_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Juvenile_Markaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_came_back_to_center', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('time_arrival_center', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_departure_center', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[(1, 'Aniqlangan'), (2, 'Markazga qabul qilingan'), (3, 'Taqsimlangan'), (4, 'Monitoring jarayonida'), (5, 'Bandlik ta’minlanish jarayonida'), (6, 'Bandligi taminlangan'), (7, 'Boshqa davlatga yuborilgan'), (8, 'Arxixda')], default=None, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('juvenile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juvenile.juvenile')),
                ('markaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.markaz')),
            ],
            options={
                'db_table': 'juvenile_markaz',
            },
        ),
        migrations.AddField(
            model_name='juvenile',
            name='accept_center_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accept_center_info', to='juvenile.juvenileacceptcenterinfo'),
        ),
        migrations.AddField(
            model_name='juvenile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_juvenile_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='juvenile',
            name='current_markaz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_markaz', to='info.markaz'),
        ),
        migrations.AddField(
            model_name='juvenile',
            name='distributed_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributed_info', to='juvenile.juveniledistributedinfo'),
        ),
        migrations.AddField(
            model_name='juvenile',
            name='employment_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_info', to='juvenile.juvenileemploymentinfo'),
        ),
        migrations.AddField(
            model_name='juvenile',
            name='monitoring_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_info', to='juvenile.juvenilemonitoringinfo'),
        ),
        migrations.AddField(
            model_name='juvenile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_juvenile_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EducationInfoJuvenile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_type', models.CharField(blank=True, choices=[(1, "Maktabgacha ta'lim"), (2, 'Maktab'), (3, 'Kasb-hunar maktabi'), (4, 'Kasb-hunar kolleji'), (5, 'Litsey'), (6, 'Texnikum'), (7, 'Maxsus ta’lim'), (8, 'OTM'), (9, 'O‘qimaydi/Ishlamaydi'), (10, 'Ishlaydi')], default=None, max_length=60, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_educationinfojuvenile_created_by', to=settings.AUTH_USER_MODEL)),
                ('juvenile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='juvenile.juvenile')),
                ('kindergarten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.kindergarten')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_educationinfojuvenile_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_info_juvenile',
            },
        ),
        migrations.CreateModel(
            name='AddressInfoJuvenile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address_mahalla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_mahalla', to='info.mahalla')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_addressinfojuvenile_created_by', to=settings.AUTH_USER_MODEL)),
                ('juvenile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='juvenile.juvenile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_addressinfojuvenile_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'address_info_juvenile',
            },
        ),
    ]
