# Generated by Django 3.2.9 on 2022-12-06 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_school'),
        ('juvenile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationinfojuvenile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.school'),
        ),
    ]
