# Generated by Django 3.2.9 on 2022-12-07 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_university'),
        ('juvenile', '0002_educationinfojuvenile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationinfojuvenile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.university'),
        ),
    ]
