# Generated by Django 3.2.9 on 2022-12-08 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_specialeducation'),
        ('juvenile', '0003_educationinfojuvenile_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationinfojuvenile',
            name='special_education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.specialeducation'),
        ),
    ]
