# Generated by Django 3.2.9 on 2022-12-09 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_vocationalschool'),
        ('juvenile', '0005_educationinfojuvenile_litsey'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationinfojuvenile',
            name='vocational_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.vocationalschool'),
        ),
    ]
