# Generated by Django 3.2.9 on 2022-12-11 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_college'),
        ('juvenile', '0006_educationinfojuvenile_vocational_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationinfojuvenile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.college'),
        ),
    ]
