# Generated by Django 3.2.9 on 2022-12-12 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_texnikum'),
        ('juvenile', '0007_educationinfojuvenile_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationinfojuvenile',
            name='texnikum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.texnikum'),
        ),
    ]
