# Generated by Django 3.2.9 on 2022-12-19 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0009_auto_20221216_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juvenile',
            name='accept_center_info',
        ),
        migrations.AddField(
            model_name='juvenile_markaz',
            name='accept_center_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accept_center_info', to='juvenile.juvenileacceptcenterinfo'),
        ),
    ]
