# Generated by Django 3.2.9 on 2022-12-19 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0010_auto_20221219_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juvenile',
            name='distributed_info',
        ),
        migrations.RemoveField(
            model_name='juvenile',
            name='employment_info',
        ),
        migrations.RemoveField(
            model_name='juvenile',
            name='monitoring_info',
        ),
        migrations.AddField(
            model_name='juvenile_markaz',
            name='distributed_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributed_info', to='juvenile.juveniledistributedinfo'),
        ),
        migrations.AddField(
            model_name='juvenile_markaz',
            name='employment_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_info', to='juvenile.juvenileemploymentinfo'),
        ),
        migrations.AddField(
            model_name='juvenile_markaz',
            name='monitoring_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_info', to='juvenile.juvenilemonitoringinfo'),
        ),
    ]
