# Generated by Django 3.2.9 on 2022-12-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0011_auto_20221219_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juveniledistributedinfo',
            name='basis_distribution',
            field=models.CharField(choices=[(1, 'Markaz xulosasi'), (2, 'Hokim qarori'), (3, "Tegishli vazirlik/tashkilot yo'llanmasi"), (4, 'Sud ajrimi'), (5, 'SSV xulosasi'), (6, 'Notarial ishonchnoma')], default=None, max_length=60, null=True),
        ),
    ]
