# Generated by Django 3.2.9 on 2022-12-20 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_texnikum'),
        ('juvenile', '0012_alter_juveniledistributedinfo_basis_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='juveniledistributedinfo',
            name='markaz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.markaz'),
        ),
    ]
