# Generated by Django 3.2.9 on 2023-01-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0013_juveniledistributedinfo_markaz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juvenile_markaz',
            name='count_came_back_to_center',
        ),
        migrations.RemoveField(
            model_name='juvenileacceptcenterinfo',
            name='count_came_back_to_center',
        ),
    ]
