# Generated by Django 3.2.9 on 2023-01-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0014_auto_20230102_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='juvenile',
            name='accepted_center_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
