# Generated by Django 3.2.9 on 2023-01-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0016_alter_juvenile_accepted_center_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juvenile',
            name='accepted_center_number',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
