# Generated by Django 3.2.9 on 2023-01-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0017_alter_juvenile_accepted_center_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juvenile_markaz',
            name='status',
            field=models.CharField(choices=[(1, 'Aniqlangan'), (2, 'Markazga qabul qilingan'), (3, 'Taqsimlangan'), (4, 'Monitoring jarayonida'), (5, 'Bandlik ta’minlanish jarayonida'), (6, 'Bandligi taminlangan'), (7, 'Boshqa davlatga yuborilgan'), (8, 'Boshqa markazga yuborilgan'), (9, 'Arxixda'), (10, 'Boshqa markazga yuborish jarayonida')], default=None, max_length=60, null=True),
        ),
    ]
