# Generated by Django 3.2.9 on 2023-01-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0018_alter_juvenile_markaz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='juveniledistributedinfo',
            name='center_opinion_file',
            field=models.FileField(blank=True, null=True, upload_to='center_opinion/'),
        ),
    ]
