# Generated by Django 3.2.9 on 2023-02-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0019_juveniledistributedinfo_center_opinion_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='juvenilemonitoringinfo',
            name='monitoring_status',
            field=models.CharField(choices=[(1, 'Monitoring jarayonida'), (2, 'RO‘TM va ITMni tugallagan'), (3, 'Ota-onasidan qaytarilgan'), (4, 'ITMdan qochgan'), (5, 'Vasiylik turidan qaytarilgan')], default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='juvenileacceptcenterinfo',
            name='arrived_reason',
            field=models.CharField(choices=[(1, 'IIB qarori'), (2, 'Sud ajrimi'), (3, "Markaz buyrug'i")], default=None, max_length=60, null=True),
        ),
    ]
