# Generated by Django 3.2.9 on 2023-02-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0020_auto_20230203_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juvenilemonitoringinfo',
            name='assimilation',
        ),
        migrations.RemoveField(
            model_name='juvenilemonitoringinfo',
            name='behavior',
        ),
        migrations.AddField(
            model_name='juvenilemonitoringinfo',
            name='school_type',
            field=models.CharField(blank=True, choices=[(1, "Maktabgacha ta'lim"), (2, 'Maktab'), (3, 'Kasb-hunar maktabi'), (4, 'Kasb-hunar kolleji'), (5, 'Litsey'), (6, 'Texnikum'), (7, 'Maxsus ta’lim'), (8, 'OTM'), (9, 'O‘qimaydi/Ishlamaydi'), (10, 'Ishlaydi')], default=None, max_length=60, null=True),
        ),
    ]
