# Generated by Django 3.2.9 on 2023-02-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0021_auto_20230204_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='juvenilemonitoringinfo',
            name='deed_and_pictures',
            field=models.FileField(blank=True, null=True, upload_to='deed_and_pictures/'),
        ),
    ]
