# Generated by Django 3.2.9 on 2023-02-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0022_juvenilemonitoringinfo_deed_and_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juvenile_markaz',
            name='status',
            field=models.CharField(choices=[(1, 'Aniqlangan'), (2, 'Markazga qabul qilingan'), (3, 'Taqsimlangan'), (4, 'Monitoring jarayonida'), (5, 'Bandlik ta’minlanish jarayonida'), (6, 'Bandligi taminlangan'), (7, 'Boshqa davlatga yuborilgan'), (8, 'Boshqa markazga yuborilgan'), (9, 'Arxixda'), (10, 'Boshqa markazga yuborish jarayonida'), (11, 'Ota-onasidan qaytarilgan'), (12, 'ITMdan qochgan'), (13, 'Vasiylik turidan qaytarilgan')], default=None, max_length=60, null=True),
        ),
    ]
