# Generated by Django 3.2.9 on 2023-03-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0024_juvenile_markaz_monitoring_markaz_tuman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juvenileemploymentinfo',
            old_name='employment',
            new_name='education_direction',
        ),
        migrations.RenameField(
            model_name='juvenileemploymentinfo',
            old_name='high_school',
            new_name='school_name',
        ),
        migrations.RemoveField(
            model_name='juvenileemploymentinfo',
            name='is_military',
        ),
        migrations.RemoveField(
            model_name='juvenileemploymentinfo',
            name='middle_school',
        ),
        migrations.AddField(
            model_name='juvenileemploymentinfo',
            name='employment_file',
            field=models.FileField(blank=True, null=True, upload_to='employment_file/'),
        ),
        migrations.AddField(
            model_name='juvenileemploymentinfo',
            name='military_conscripted_file',
            field=models.FileField(blank=True, null=True, upload_to='military_conscripted_file/'),
        ),
        migrations.AddField(
            model_name='juvenileemploymentinfo',
            name='school_applied_file',
            field=models.FileField(blank=True, null=True, upload_to='school_applied_file/'),
        ),
    ]
