# Generated by Django 3.2.9 on 2023-03-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0025_auto_20230308_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='prophylacticinspector',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
