# Generated by Django 3.2.9 on 2023-03-23 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_alter_district_extra_id'),
        ('juvenile', '0026_prophylacticinspector_certificate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='prophylacticinspector',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district', to='info.district'),
        ),
    ]
