# Generated by Django 3.2.9 on 2023-03-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0027_prophylacticinspector_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='juveniledistributedinfo',
            name='training_file',
            field=models.FileField(blank=True, null=True, upload_to='training_file/'),
        ),
    ]
