# Generated by Django 3.2.9 on 2023-03-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0028_juveniledistributedinfo_training_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='juvenileemploymentinfo',
            name='is_accepted_to_school',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='juvenileemploymentinfo',
            name='is_applied_document',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='juvenileemploymentinfo',
            name='is_military',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
