# Generated by Django 3.2.9 on 2023-07-02 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0029_auto_20230323_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juvenile_markaz',
            name='juvenile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juvenile_markaz', to='juvenile.juvenile'),
        ),
    ]
