# Generated by Django 3.2.9 on 2023-11-16 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0030_alter_juvenile_markaz_juvenile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionToWhom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('pinfl', models.CharField(blank=True, max_length=14)),
                ('distribution_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='juvenile.juveniledistributedinfo')),
            ],
        ),
    ]
