# Generated by Django 3.2.9 on 2023-11-21 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juvenile', '0030_alter_juvenile_markaz_juvenile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionToWhom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pinfl', models.CharField(blank=True, max_length=14, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_distributiontowhom_created_by', to=settings.AUTH_USER_MODEL)),
                ('distribution_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='juvenile.juveniledistributedinfo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_distributiontowhom_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kimga topshirilgani',
                'verbose_name_plural': 'Kimga topshirilgani',
                'db_table': 'distribution_to_whom',
            },
        ),
    ]
