# Generated by Django 3.2.9 on 2023-11-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0031_distributiontowhom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributiontowhom',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='distributiontowhom',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='distributiontowhom',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='distributiontowhom',
            name='pinfl',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
