# Generated by Django 3.2.9 on 2023-11-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0032_alter_distributiontowhom_distribution_info'),
        ('juvenile', '0032_auto_20231120_1221'),
    ]

    operations = [
    ]
