# Generated by Django 3.2.9 on 2023-11-21 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0032_auto_20231120_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributiontowhom',
            name='distribution_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributes', to='juvenile.juveniledistributedinfo'),
        ),
    ]
