# Generated by Django 3.2.9 on 2023-12-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0033_alter_distributiontowhom_distribution_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributiontowhom',
            options={'verbose_name': 'Kimga topshirilgani', 'verbose_name_plural': 'Kimga topshirilgani'},
        ),
        migrations.AlterModelTable(
            name='distributiontowhom',
            table='distribution_to_whom',
        ),
    ]
