# Generated by Django 3.2.9 on 2024-01-24 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0034_psychologycondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='juveniledistributedinfo',
            name='psychology_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributed_infos', to='juvenile.psychologycondition'),
        ),
    ]
