# Generated by Django 3.2.9 on 2023-12-18 11:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juvenile', '0034_auto_20231215_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributiontowhom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 18, 11, 15, 45, 334079, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributiontowhom',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_distributiontowhom_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distributiontowhom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='distributiontowhom',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_distributiontowhom_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='distributiontowhom',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
