# Generated by Django 3.2.9 on 2024-02-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0035_juveniledistributedinfo_psychology_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfojuvenile',
            name='passport_seria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
