# Generated by Django 3.2.9 on 2024-01-18 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juvenile', '0035_auto_20231218_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologyCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_psychologycondition_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juvenile_psychologycondition_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bola psixologik holati',
                'verbose_name_plural': 'Bola psixologik holati',
                'db_table': 'psychology_condition',
            },
        ),
        migrations.AddField(
            model_name='juveniledistributedinfo',
            name='psychology_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributed_infos', to='juvenile.psychologycondition'),
        ),
    ]
