# Generated by Django 3.2.9 on 2024-07-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0036_alter_personalinfojuvenile_passport_seria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juvenileacceptcenterinfo',
            name='determined_location',
            field=models.CharField(choices=[('1', 'Bozor'), ('2', 'Yer-to‘la va chor-doq'), ('3', "Ko'cha"), ('4', 'Boshqa joylar'), ('5', 'Boshqa davlatlardan')], default=None, max_length=60, null=True),
        ),
    ]
