# Generated by Django 3.2.9 on 2024-01-19 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0036_auto_20240118_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psychologycondition',
            options={},
        ),
    ]
