# Generated by Django 3.2.9 on 2024-07-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0037_alter_juvenileacceptcenterinfo_determined_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationinfojuvenile',
            name='school_type',
            field=models.CharField(blank=True, choices=[(1, "Maktabgacha ta'lim"), (2, 'Maktab'), (3, 'Kasb-hunar maktabi'), (4, 'Kasb-hunar kolleji'), (5, 'Litsey'), (6, 'Texnikum'), (7, "Maxsus ta'lim"), (8, 'OTM'), (9, "O'qimaydi/Ishlamaydi"), (10, 'Ishlaydi')], default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='juvenile_markaz',
            name='status',
            field=models.CharField(choices=[(1, 'Aniqlangan'), (2, 'Markazga qabul qilingan'), (3, 'Taqsimlangan'), (4, 'Monitoring jarayonida'), (5, "Bandlik ta'minlanish jarayonida"), (6, 'Bandligi taminlangan'), (7, 'Boshqa davlatga yuborilgan'), (8, 'Boshqa markazga yuborilgan'), (9, 'Arxixda'), (10, 'Boshqa markazga yuborish jarayonida'), (11, 'Ota-onasidan qaytarilgan'), (12, 'ITMdan qochgan'), (13, 'Vasiylik turidan qaytarilgan')], default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='juvenileacceptcenterinfo',
            name='arrived_reason',
            field=models.CharField(choices=[('1', 'IIB qarori'), ('2', 'Sud ajrimi'), ('3', "Markaz buyrug'i")], default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='juvenileacceptcenterinfo',
            name='determined_location',
            field=models.CharField(choices=[('1', 'Bozor'), ('2', "Yer-to'la va chor-doq"), ('3', "Ko'cha"), ('4', 'Boshqa joylar'), ('5', 'Boshqa davlatlardan')], default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='juvenileacceptcenterinfo',
            name='have_been_in_itm_reason',
            field=models.CharField(choices=[('1', 'Qaror bilan chiqarilgan'), ('2', 'Qochgan')], default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='juvenileacceptcenterinfo',
            name='have_been_in_rotm_reason',
            field=models.CharField(choices=[('1', 'Qaror bilan chiqarilgan'), ('2', 'Qochgan')], default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='juveniledistributedinfo',
            name='foreign_to_whom_given',
            field=models.CharField(choices=[(1, "Ota-onasi yoki uni o'rnini bosuvchi shaxsga"), (2, 'Chet-el Elchixonasiga'), (3, 'Chet-el Markazi xodimiga')], default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='juveniledistributedinfo',
            name='type_healthcare_facility',
            field=models.CharField(choices=[(1, 'Ruhiy-asab kasalliklari dispanseri'), (2, 'Narkologiya dispanseri'), (3, 'Teri-tanosil dispanseri'), (4, 'Sil kasaliklari dispanseri'), (5, "Sog'ligida nuqsoni bor bolalar muassasasi")], default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='juvenilemonitoringinfo',
            name='monitoring_status',
            field=models.CharField(choices=[(1, 'Monitoring jarayonida'), (2, "RO'TM va ITMni tugallagan"), (3, 'Ota-onasidan qaytarilgan'), (4, 'ITMdan qochgan'), (5, 'Vasiylik turidan qaytarilgan')], default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='juvenilemonitoringinfo',
            name='school_type',
            field=models.CharField(blank=True, choices=[(1, "Maktabgacha ta'lim"), (2, 'Maktab'), (3, 'Kasb-hunar maktabi'), (4, 'Kasb-hunar kolleji'), (5, 'Litsey'), (6, 'Texnikum'), (7, "Maxsus ta'lim"), (8, 'OTM'), (9, "O'qimaydi/Ishlamaydi"), (10, 'Ishlaydi')], default=None, max_length=60, null=True),
        ),
    ]
