# Generated by Django 3.2.9 on 2024-01-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0037_alter_psychologycondition_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='juvenileacceptcenterinfo',
            name='is_in_prophylactic',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='juvenileacceptcenterinfo',
            name='is_sudlangan',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='juvenileparent',
            name='is_47_criminal',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='juvenileparent',
            name='is_in_prophylactic',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='juvenileparent',
            name='is_sudlangan',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='personalinfojuvenile',
            name='is_in_prophylactic',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='personalinfojuvenile',
            name='is_sudlangan',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
