# Generated by Django 3.2.9 on 2024-01-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0038_auto_20240125_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juvenileacceptcenterinfo',
            name='is_in_prophylactic',
        ),
        migrations.RemoveField(
            model_name='juvenileacceptcenterinfo',
            name='is_sudlangan',
        ),
    ]
