# Generated by Django 3.2.9 on 2024-12-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenile', '0039_juveniledistributedinfo_prophylactic_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juvenilemonitoringinfo',
            name='monitoring_status',
            field=models.CharField(choices=[(1, 'Monitoring jarayonida'), (2, "RO'TM va ITMni tugallagan"), (3, 'Ota-onasidan qaytarilgan'), (4, 'ITMdan qochgan'), (5, 'Vasiylik turidan qaytarilgan'), (6, 'Jinoyatchilik hisobga olingan')], default=None, max_length=60, null=True),
        ),
    ]
