# Generated by Django 3.2.9 on 2023-02-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_medicallist_extra_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='extra_id',
            field=models.SmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
