# Generated by Django 3.2.9 on 2023-02-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_region_extra_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='extra_id',
            field=models.SmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
