# Generated by Django 3.2.9 on 2023-03-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_markaztuman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='extra_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
