# Generated by Django 3.2.9 on 2024-01-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_alter_district_extra_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(max_length=500)),
                ('refresh', models.CharField(max_length=500)),
                ('date_time_access', models.DateTimeField()),
                ('date_time_refresh', models.DateTimeField()),
            ],
        ),
    ]
